# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Portfolio - Heloisa Munaretto
email: helo.munaretto@gmail.com
description: "Graphic designer working with UI development about 6 years. I have solid experience creating high-fidelity mockups and implementing with HTML/CSS. Besides that I have strong visual design skills, including layout, color theory, typography and usability."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://helomunaretto.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: helomunaretto
github_username:  helomunaretto
linkedin_username: heloisa-munaretto-3b36a524
google_analytics: UA-114410196-1

# Build settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
